version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foody-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/foody'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
    ports:
      - "8080:8080"
    networks:
      - foody-postgres-net
    restart: unless-stopped

  postgres:
    image: 'postgres:16-alpine'
    container_name: foody-db
    environment:
      - 'POSTGRES_DB=foody'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - foody-postgres-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  foody-postgres-net:
    driver: bridge

volumes:
  postgres-data:
    driver: local
